### ISSUE TITLE
Node face compare demo not working with TS

### ISSUE THREAD

**Issue by AnthonyLzq** [vladmandic/face-api#151] opened 2023-01-15 07:04 UTC
**Issue Description**

I'm trying to run the `demo/node-face-compare.js` script, but I have migrated it to [TS](https://gist.github.com/AnthonyLzq/c50248f059d82db484136bbc2464b39f). However, TypeScript is complaining about the type of the tensor with the following error:

```bash
Argument of type 'Tensor3D | Tensor4D' is not assignable to parameter of type 'TNetInput'.
  Type 'Tensor3D' is not assignable to type 'TNetInput'.
    Type 'Tensor<Rank.R3>' is not assignable to type 'Tensor4D'.
      Types of property 'shape' are incompatible.
        Type '[number, number, number]' is not assignable to type '[number, number, number, number]'.
          Source has 3 element(s) but target requires 4.ts(2345)
```

Image for reference:

![image](https://user-images.githubusercontent.com/43073718/212527503-7ab4a815-9c7a-429e-a56f-5fa04c6604b8.png)

**Steps to Reproduce**

Try to run this [script](https://gist.github.com/AnthonyLzq/c50248f059d82db484136bbc2464b39f) with `ts-node` or something.

**Expected Behavior**

To work, I guess, I suppose this is an issue with the types.

**Environment**

- Module version? `@vladmandic/face-api": "^1.7.8` and `"@tensorflow/tfjs-node": "^4.2.0"`. 
- Built-in demo or custom code? Demo, but with TS instead of JS.
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? CommonJS.
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? NodeJS v18.12.1.
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? 5.19.17-2-MANJARO.
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)? No, only `tsc` and `ts-node` executing it directly.

**Comment by vladmandic** [comment] 2023-01-15 12:32
i'm going to assume this is similar to other issue you've just created - https://github.com/vladmandic/human/issues/328
make sure that models are actually correctly loaded, not just last error message.

**Comment by AnthonyLzq** [comment] 2023-01-15 17:44
In fact, this isn't similar, this is just a type error.

**Comment by vladmandic** [comment] 2023-01-15 17:48
ok, i'll take a look

**Comment by vladmandic** [comment] 2023-01-21 14:04
i just tried to reproduce using your script and it works just fine here - i guess it up to project setup - please share full reproduction project that i can just clone (`tsconfig.json` & `package.json` are key)

**Comment by vladmandic** [comment] 2023-01-27 16:01
any updates?

**Comment by AnthonyLzq** [comment] 2023-01-29 03:17
Hi there, last week was crazy for me, did not have time to check it, I will review it right away. Sorry for the delay.

**Comment by AnthonyLzq** [comment] 2023-01-29 03:38
Here is the [repo](https://github.com/AnthonyLzq/face-api-demo) with the issue.

**Comment by vladmandic** [comment] 2023-01-29 15:09
ok, i see what the issue is, but i don't see a way to resolve it without major change on how `face-api` is built.  

the error is misleading, the  core issue is that `Tensor` type signatures are not the same in `@tensorflow/tfjs` (browser package) and `@tensorflow/tfjs-node` (nodejs package)

you can confirm by basically doing:

```js
const tensor = tf.node.decodeImage(buffer, 3) as faceApi.tf.Tensor3D
```

easiest temporary solution is to relax that typecheck:

```js
  const faces = await faceApi.detectAllFaces(tensor as any, optionsSSDMobileNet)
```

extracting and bundling different typedefs for different flavors of `tfjs` during `faceapi` build would be out-of-scope for now. i did restructure some typedefs, so do a git pull anyhow.

btw, off-topic, but if you're building for node *and* using esm, you may want to import node flavor of `faceapi` explictly as its auto import resolver may pick browser esm version:

```js
import faceApi from '@vladmandic/face-api/dist/face-api.node'
```

**Comment by vladmandic** [comment] 2023-01-31 13:04
as per previous note, i'm closing the issue as its cosmetic only and full fix would be out of scope for now.

**Closed by vladmandic** 2023-01-31 13:04 UTC
Labels: question
