### ISSUE TITLE
Process images sequentially with wasm

### ISSUE THREAD

**Issue by dat0825** [vladmandic/face-api#113] opened 2022-06-27 16:32 UTC
**Issue Description**

when I use wasm instead of webgl, at the same time with 3 images input, it may be run sequentially with times order by are `0.827s`, `1.601s` and `2.58s`. Meanwhile, if i use webgl the time order by are `0.57s`, `0.57s ` and `0.51s`.

**Environment**

- Module version 1.6.10
- Type of module used `esm`
- I'm using Chrome version 102

**Comment by vladmandic** [comment] 2022-06-27 18:38
after app has been initialized, please provide output of:

```js
const simd = await faceapi.tf.env().getAsync('WASM_HAS_SIMD_SUPPORT');
const mt = await faceapi.tf.env().getAsync('WASM_HAS_MULTITHREAD_SUPPORT');
console.log({ simd, mt });
```

**Comment by dat0825** [comment] 2022-06-28 01:37
> after app has been initialized, please provide output of:
> 
> ```js
> const simd = await faceapi.tf.env().getAsync('WASM_HAS_SIMD_SUPPORT');
> const mt = await faceapi.tf.env().getAsync('WASM_HAS_MULTITHREAD_SUPPORT');
> console.log({ simd, mt });
> ```

Output:
WASM_HAS_SIMD_SUPPORT: `true`
WASM_HAS_MULTITHREAD_SUPPORT: `false`

**Comment by dat0825** [comment] 2022-06-28 02:27
I resolved by set `await faceapi.tf.ENV.set('WASM_HAS_MULTITHREAD_SUPPORT', true)`
Thanks for the help

**Comment by vladmandic** [comment] 2022-06-28 05:37
WASM multithreading is either allowed by browser or not, you cannot enable it from TFJS side without browser support.
And the fact that on your system its not enabled fully explains why do you see performance issues as described.

You can try setting `chrome://flags/#enable-experimental-webassembly-features` and see if that helps.

**Comment by vladmandic** [comment] 2022-07-02 07:38
Any updates from your side on why Chrome on your system is reporting single-threaded capability only?

**Comment by dat0825** [comment] 2022-07-02 09:38
I'm faceing with a problem in chrome that `SharedArrayBuffer is not defined`. I'm trying set `Cross-Origin-Opener-Policy: same-origin Cross-Origin-Embedder-Policy: require-corp` into response header by using service worker, but it's fail with `opaque response`

**Comment by vladmandic** [comment] 2022-07-02 09:53
changing response headers in such way is not allowed (doesn't matter if its in a main thread or in a service worker). only difference is that in service worker it will try do it anyhow and result in who-knows-what.

only way to change response headers client-side is when running in a browser extension context.

cant you set correct headers server-side?

**Comment by dat0825** [comment] 2022-07-03 16:39
But after I config webserver COOP COEP, The requests from third party are blocked 
```
add_header "Cross-Origin-Embedder-Policy"  "require-corp";
add_header "Cross-Origin-Opener-Policy"  "same-origin";
```

**Comment by vladmandic** [comment] 2022-07-03 18:15
Ah, yes, the magic of origin headers - Google really messed that up. It was fine until few month ago and now it's totally broken, up to a point where using WASM is a nightmare right now.

**Comment by dat0825** [comment] 2022-07-04 01:54
I can resolve this problem by using  [Chrome Origin Trials](https://developer.chrome.com/origintrials/#/register_trial/303992974847508481). But it doesn't stabilize for my product. Thanks for the help.

**Comment by vladmandic** [comment] 2022-07-04 05:15
i'm going to close the issue as root cause is not in the product, but feel free to post further questions/comments in this thread.

**Closed by vladmandic** 2022-07-04 05:15 UTC
Labels: question
