### ISSUE TITLE
Error while trying to recognise faces in a realtime video

### ISSUE THREAD

**Issue by CDanSantana** [vladmandic/face-api#112] opened 2022-06-17 19:20 UTC
**Issue Description**

Hi!

First of all, thanks for publishing and keeping this project up to date!

I'm trying to use it, but I have some problem... What am I doing wrong?

When I try to recognise faces in a realtime video it throws an error.

```
face-api.js:4685 Uncaught (in promise) Stack table collapsed
face-api.js:4685 Uncaught (in promise) Error: Box.constructor - expected box to be IBoundingBox | IRect, instead have {"left":0.15384615384615385,"top":null,"right":0.15384615384615385,"bottom":null}
    at new lt (face-api.js:4685:10546)
    at new Fo (face-api.js:4685:12758)
    at Ho.extractBoxes (face-api.js:4685:75061)
    at async Ho.detect (face-api.js:4685:73592)
    at async Ho.locateFaces (face-api.js:4685:77011)
```

**Steps to Reproduce**

1. Created project with npm init
2. Installed face-api and other dependencies with npm install
3. Tryed to run the attached code

**Expected Behavior**

The library should recognise faces.

**Environment**

- Module version? 1.6.10
- Built-in demo or custom code? custom code
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? js
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Google Chrome 102.0.5005.63
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Windows 10 x64
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)? none

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
[gist: served from a ejs view page, in conjunction with Express](https://gist.github.com/CDanSantana/319509d5e39fa5a6cd5ccfafdff87835)

**Comment by vladmandic** [comment] 2022-06-17 19:25
I'll take a look, but it may be slightly slower response than usual as I'm on traveling on vacation right now.

**Comment by vladmandic** [comment] 2022-06-18 05:39
the code posted in gist is not complete, i don't know how the methods are invoked (e.g, addVideoStream is not there). can you post a full reproduction, including your html as well?

from the top of my head, this sounds like a possible race scenario so actual order of events is critical.

on top of that, few quick comments:
- never use `setInterval` as you don't know how long will the pass take, so you may end up with multiple inferences running at the same time which cannot work (especially during first frame when models are still warming up).  
  look at demos and examples, but in general `requestAnimationFrame` is your friend
- don't create new options object on each frame - it should be created only once outside of the loop at the same time when you load models  
  (e.g. `new faceapi.TinyFaceDetectorOptions`)
- there is no benefit of using `tiny` vs `ssd` model unless you're running on a mobile device with extremely limited memory. otherwise `ssd` is better in all cases.

**Comment by CDanSantana** [comment] 2022-06-18 13:43
Thank you so much for taking the time to look at this on your vacation!

I'll be organizing the code, applying your suggestions, and if the error persists I'll come back with something more organized...

About the tine model, it's because I'm planning to run on mobile devices, with some other tasks on the same page...

One more offtopic question... About your other project "Human", it seems to have a lot more features than the face-api... Can it be used on devices with limited resources?

One more time, thank you for taking the time to look at this!

**Comment by vladmandic** [comment] 2022-06-18 14:49
Re: `tiny` vs `ssd` faceapi models - tiny is not that much faster, even on low-end mobile devices. only big difference is memory - if you have a very limited memory on a device (e.g. mobile phone with 2gb only), then use `tiny`. for everything else, I'd suggest `ssd`

Re: **FaceAPI** vs **Human** - by default `human` does a lot more, but most of additional functionality can be turned off, so it can run on mobile devices. But again, question is of memory - it definitely uses far more memory, I wouldn't suggest it on mobile phones with less than 4GB RAM overall (which means its ok for all newer phones, but not stuff from couple of years ago). I'm using it on my old S10 and works without problems (and of course even better on my new S22).

One other major difference is that `human` can work in a web worker so if you have a low-power device, it would not block execution of the main thread (it doesn't mean it would run faster overall, it just means that overall responsiveness of an application does not suffer as detection happens in the background). `FaceAPI` internally uses DOM quite a lot, so it can only run in a main thread.

**Comment by CDanSantana** [comment] 2022-06-18 15:55
Thank you! I edited my script with your suggestions, and it's working!

Looks like I was also trying to use webgl or something related to gpu, and tensorflow was complaining that there was no context for it...

Is using this line on startup a bad idea?

await faceapi.tf.setBackend('cpu');

Thanks!

**Comment by vladmandic** [comment] 2022-06-18 17:29
`cpu` backend is by far slowest, i wouldn't recommend it for anything but tests.

best backends are: 
1. `webgpu` - still experimental and requires debug flag in chrome, so not recommended yet, but will be soon i hope
2. `webgl` - did you get **"lost context"** or **"no context"** or **"cannot get context"**error? those two are very different. you said you're using chrome 102, so only reason for **no context** is if you already allocated 2d context on canvas (as only either 2d or webgl can be allocated for same canvas object, not both). but you're passing video to faceapi, so faceapi internally allocates temporary canvas for you (thats the only way to get pixel data), so that really should never happen. on the other hand **lost context** most likely happens due to gpu memory limits (either very low gpu memory to start with or there is a memory leak)
3. `wasm` good option if you're using system without a gpu, but binary compatibility of wasm binaries can be an issue
4. `cpu` always works, but its order of magnitude slower than anything

i would recommend spending some time to get `webgl` working.

**Comment by CDanSantana** [comment] 2022-06-20 22:08
Thanks!

The error was about no context...

I'm considering that most of my target users are on either mobile devices or PCs with little or no dedicated video memory...

Thanks again! I will keep on studying and experimenting!

**Comment by vladmandic** [comment] 2022-06-21 05:01
since original item is resolved, im closing the issue - but feel free to post additional msgs to this thread and i'll assist if i can.

**Closed by vladmandic** 2022-06-21 05:01 UTC
Labels: question
