### ISSUE TITLE
findBestMatch - is not working correctly

### ISSUE THREAD

**Issue by danies8** [vladmandic/face-api#69] opened 2021-09-29 13:11 UTC
Hi ,
When I inserted this face into db :
![cGc](https://user-images.githubusercontent.com/1079689/135274605-2fb8a6c3-36ec-417d-b08e-a4a10c2dfb2a.jpg)
and compared with this, he found the first one! why ? he should return unknown.
![cGc40](https://user-images.githubusercontent.com/1079689/135274717-4dfa4126-f63b-4ef5-b24d-a99b717c722a.jpg)
distance Threshold 0.5 and the actual threshold
"bestMatchPerson": {
"_label": "2",
"_distance": 0.44472999761672266
}
What do I miss ? the image inputs and compare are not good ?
Thanks in advance.

**Comment by vladmandic** [comment] 2021-09-29 13:28
what exactly did you use? if you call explict match, it always returns a distance value. if you call `findBestMatch`, it will return best match if its above `distanceThreshold`

actual code: 

```ts
public findBestMatch(queryDescriptor: Float32Array): FaceMatch {
    const bestMatch = this.matchDescriptor(queryDescriptor);
    return bestMatch.distance < this.distanceThreshold ? bestMatch : new FaceMatch('unknown', bestMatch.distance);
  }
```

**Comment by vladmandic** [comment] 2021-09-29 13:34
there seems to be a typo in the method  

fixed via <https://github.com/vladmandic/face-api/commit/1b4580dd6ee175681655d9f4a9011310afc699a9#diff-e20cfb0253557048cbdfaa2de9a86d00cafa78932dd7ba9fb3ae6289b109473e>

new version is published

**Comment by danies8** [comment] 2021-09-29 13:46
I used this code:
```
const distanceThreshold=0.5;
let matcher = new faceapi.FaceMatcher(labeledFaceDescriptors, distanceThreshold);
bestMatchPerson = matcher.findBestMatch(faces[0].descriptor);
```

**Comment by danies8** [comment] 2021-09-29 14:14
I check with another person that is not in DB:
![image](https://user-images.githubusercontent.com/1079689/135286133-ca72b805-df54-42a3-ae3e-522ce07a3d85.png)
And I got this people:
![103](https://user-images.githubusercontent.com/1079689/135286250-305ce1ed-9ee1-49b3-b5c8-61272eb481d5.jpeg)
"bestMatchPerson": {
        "_label": "103",
        "_distance": 0.33258788746528983
    }

**Comment by vladmandic** [comment] 2021-09-29 14:31
i cannot reproduce the issue. post a link to a working gist (complete).

**Comment by danies8** [comment] 2021-09-29 14:35
Here routing of register and compare all:
https://gist.github.com/danies8/2a4bec02851f3952f1e102f9120d0997

**Comment by vladmandic** [comment] 2021-09-29 16:41
so what is the problem??  
detected `distance` is 0.33 and `distanceThreshold` is 0.5  
clearly `distance` is less than that so it returns a match!?!?!

and when someone asks for reproducible code, **make an effort** to write a reproduction that works  
copy & paste from your app is not helpful  

btw, this is the code i just wrote to test your two images  
look how few dependencies it has and how short it is:

```js
const fs = require('fs');
const tf = require('@tensorflow/tfjs-node');
const faceapi = require('../dist/face-api.node.js');

let optionsSSDMobileNet;
const minConfidence = 0.1;
const distanceThreshold = 0.5;
const modelPath = '../model';
const labeledFaceDescriptors = [];

async function initFaceAPI() {
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
  await faceapi.nets.faceLandmark68Net.loadFromDisk(modelPath);
  await faceapi.nets.faceRecognitionNet.loadFromDisk(modelPath);
  optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options({ minConfidence, maxResults: 1 });
}

async function getDescriptor(imageFile) {
  const buffer = fs.readFileSync(imageFile);
  const tensor = tf.node.decodeImage(buffer, 3);
  const faces = await faceapi.detectAllFaces(tensor, optionsSSDMobileNet)
    .withFaceLandmarks()
    .withFaceDescriptors();
  tf.dispose(tensor);
  return (faces && faces[0]) ? faces[0].descriptor : null;
}

async function registerImage(inputFile) {
  const descriptor = await getDescriptor(inputFile);
  if (descriptor) {
    const labeledFaceDescriptor = new faceapi.LabeledFaceDescriptors('1.png', [descriptor]);
    labeledFaceDescriptors.push(labeledFaceDescriptor);
  }
}

async function findBestMatch(inputFile) {
  const matcher = new faceapi.FaceMatcher(labeledFaceDescriptors, distanceThreshold);
  const descriptor = await getDescriptor(inputFile);
  return matcher.findBestMatch(descriptor);
}

async function main() {
  await initFaceAPI();
  await registerImage('1.png');
  const bestMatch = await findBestMatch('2.jpg');
  console.log(bestMatch);
}
main();
```

and you have **NOT addressed issues** or suggestions i made earlier:
- use only models you actually need  
  for example, i dont see why you have age&gender detection
- youre still loading models again and again
- youre still writing temp file just to read it back immediately  
  when you already have a buffer  
- youre still using canvas library instead of native decoding
- youre still assuming that number of detected faces in each image is exactly 1  
  not checking for more and not even checking if 1st face is valid
- (only thing youve fixed is to use `writeFileSync`)

until you clean up your code i will not address any of your issues

**Closed by vladmandic** 2021-09-29 16:41 UTC
Labels: bug

**Comment by danies8** [comment] 2021-09-29 19:03
>1.  so what is the problem??
> detected `distance` is 0.33 and `distanceThreshold` is 0.5
> clearly `distance` is less than that so it returns a match!?!?!
But is not the right person, how can i give enter ???

2.youre still loading models again and again
I used these modals in loading process when app is loading
const tf = require('@tensorflow/tfjs-node');
const faceapi = require('@vladmandic/face-api');
const path = require('path');

async function loadModals() {
      const faceDetectionNet = new faceapi.FaceDetectionNet();
      const modelPath = '../../node_modules/@vladmandic/face-api/model';
      await faceDetectionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ageGenderNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceLandmark68Net.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceRecognitionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceExpressionNet.loadFromDisk(path.join(__dirname, modelPath));
}
module.exports = { loadModals }

3.I valid for first face
   youre still using canvas library instead of native decoding
 // 2. Create tensor
      let arr = imageStrEncodedBase64.split(',');
      let bstr = atob(arr[1]); 
      let n = bstr.length; 
      let u8arr = new Uint8Array(n);
      while(n--){
          u8arr[n] = bstr.charCodeAt(n);
      }
      const tensor = tf.node.decodeImage(u8arr, 3);
4.
if (!faces) {
        let detectAllFacesMessage = "compare all:faces is null or undefined";
        utils.logger.log({
          level: 'error',
          message: detectAllFacesMessage,
          label: 'faceRecognition.ts'
        });
        return { success: false, error: detectAllFacesMessage }
      }

**Comment by vladmandic** [comment] 2021-09-29 19:50
If distance is above threshold, you don't get a person, you get 'unknown'.

This is working as expected. Issue is closed.

**Comment by danies8** [comment] 2021-09-29 19:54
So, how I can know if it right person or not ? 
I will ask differently, how can i know if to let him enter or not?

**Comment by vladmandic** [comment] 2021-09-29 20:10
i think you got entire concept wrong - `distance` means how different two faces are. distance of 0 means identical. so if distanced is below a threshold, you get a match.

**Comment by danies8** [comment] 2021-09-29 20:23
I need to learn my pictures and define what is the distance that is right to my organization.
I see good match is up to 0.35  and above is not good match.
So 0.35 is the distance that above it will not enter, and below it it will enter.
While threshold is 0.5.
I understood you right ?
