### ISSUE TITLE
Difference results from desktop and mobile

### ISSUE THREAD

**Issue by toguvr** [vladmandic/face-api#92] opened 2021-12-31 02:50 UTC
I had created a node api to show similarity and I want use my app and my website, when I send from my website to the nodejs (where is running this library), I receive a number on web from desktop and from mobile. But when I send from my app. I really don't know why, but the answer of similarity is coming wrong and I am doing the same call. But if the problem is the cam, why when I send from my website but on mobile it work?! Do u know what can be? Thanks for all your help.

**Comment by vladmandic** [comment] 2021-12-31 03:33
provide details on which tfjs backend is used for both browser and nodejs environment and some actual data - saying its *different* doesn't really help.

**Comment by vladmandic** [comment] 2021-12-31 03:57
provide some details - what does *different* mean?  

also, in all cases backend is the same nodejs app?  
and image is uploaded to backend using same nodejs api?  

if that is true, then only difference can be on the client side how image is prepared  
are you resizing image before uploading it? does it have same aspect ratios? etc.

**Comment by toguvr** [comment] 2021-12-31 14:35
also, in all cases backend is the same nodejs app? Yes
and image is uploaded to backend using same nodejs api? i am appending on a formData and sending

if that is true, then only difference can be on the client side how image is prepared
are you resizing image before uploading it? does it have same aspect ratios? etc.
i will send here the code.

in app (expo react native):
using camera from expo-camera...
```
 <Camera
              type={cameraType}
              flashMode={flashMode}
              style={{ flex: 1 }}
              ref={(r) => {
                camera = r;
              }}
            >
            
            the function:
            
   const __takePicture = async () => {
    if (!camera) return;
    const photo = await camera.takePictureAsync({
      quality: 0.9,
    });

    setPreviewVisible(true);
    setCapturedImage(photo);
  };
  
  
  const uploadRecognize = async () => {
    let localUri = capturedImage.uri;
    let filename = localUri.split("/").pop();
    let match = /\.(\w+)$/.exec(filename!);
    let type = match ? `image/${match[1]}` : `image`;

    const newCapturedImage = {
      uri: localUri,
      name: filename,
      type,
    };

    setPreview1(user.avatar_url);
    setPreview2(localUri);

    setLoading(true);
    // criando um formData para upload do arquivo
    const formData = new FormData();
    formData.append("image", newCapturedImage);
    formData.append("compareUrl", user.avatar_url);
    try {
      const response = await axios.post(
        "https://raxaback.herokuapp.com/",
        formData
      );
      setDistance(response.data);
      console.log(response.data);
      response.data.samePerson
        ? Alert.alert("Reconhecido!")
        : Alert.alert("Nao reconhecido!");
    } catch (err) {
      console.log(err.response);
      Alert.alert(
        err?.response?.data?.message || "Foto não atualizada, tente novamente."
      );
    } finally {
      setLoading(false);
    }
  };
```
 at website: (i am using camera from lib react-html5-camera-photo):
 
     ```
  <Camera onTakePhoto={handleTakePhoto} />
 const handleTakePhoto = useCallback(async (dataUri) => {
    await onSelectionChanged(dataUri);
    callback(dataUri);
  }, []);
  
  function dataURLtoBlob(dataurl) {
    var arr = dataurl.split(","),
      mime = arr[0].match(/:(.*?);/)[1],
      bstr = atob(arr[1]),
      n = bstr.length,
      u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new Blob([u8arr], { type: mime });
  }
  const callback = async (image: string) => {
    setLoading(true);

    const blobImage = dataURLtoBlob(image);

    // criando um formData para upload do arquivo
    const formData = new FormData();
    formData.append("image", blobImage);
    formData.append("compareUrl", user?.avatar_url);
    try {
      const response = await axios.post(
        "https://raxaback.herokuapp.com/",
        formData
      );
      console.log(response.data);

      return toast({
        title: "Foto atualizada!",
        status: "success",
        position: "top-right",
        duration: 3000,
        isClosable: true,
      });
    } catch (err) {
      toast({
        title: "Foto não atualizada, tente novamente.",
        status: "error",
        position: "top-right",
        duration: 3000,
        isClosable: true,
      });
    } finally {
      setLoading(false);
    }
  };
```

**Comment by vladmandic** [comment] 2021-12-31 15:04
since in both cases you upload image to server, can you save it as a file and look at image differences?

**Comment by toguvr** [comment] 2021-12-31 18:25
very nice idea! I tried but its only saving in s3 when i send a request from postman, from web and from app they arent uploading to aws i dont know why... (same api)

**Comment by vladmandic** [comment] 2021-12-31 19:42
well, thats something to troubleshoot - you need to get actual images from both cases to get reproducible scenario

**Comment by vladmandic** [comment] 2022-01-01 12:37
btw, since both web and mobile app are eventually processed by nodejs app, can you save images just before it gets processed?

**Comment by toguvr** [comment] 2022-01-01 13:57
I don't know why, but I changed de expo-camera to de imagepicker lib and worked. I really don't know the problem with the expo camera, but the problem is because the imagepicker I can't manage the camera

**Comment by vladmandic** [comment] 2022-01-01 17:37
i wish i could explain, but i don't use `expo`. anyhow, it doesn't seem like its a issue with `face-api`?

**Comment by vladmandic** [comment] 2022-01-02 12:23
closing as resolved...

**Closed by vladmandic** 2022-01-02 12:23 UTC
Labels: question
