### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by srour** [vladmandic/face-api#98] opened 2022-03-21 02:47 UTC
**Issue Description**
I took the code from /demo/node-image.js and turned it into a module with a callback. Maybe not the most elegant solution but I'm looking for something quick and dirty for the moment. 

I have another module that calls into this module sequentially based off of an array of filenames. Everything functions as I expect, however the total memory footprint for the node process continues to expand until the OS kills the process. 

I am processing over 300k images, but by the time the memory issues occur it's only at like 1k images processed.

Is there anything obviously leaking in this module that I should be aware of? I'm new to TensorFlow so dont know really what's going on yet. I'm wondering if calling the load models functions over and over again is linearly adding to the memory footprint.

Here is the code - almost an exact replica of the demo code:

const fs = require("fs");
const image = require("@canvas/image"); // @canvas/image can decode jpeg, png, webp
const log = require("@vladmandic/pilogger");
const tf = require("@tensorflow/tfjs-node"); // in nodejs environments tfjs-node is required to be loaded before face-api
const faceapi = require("@vladmandic/face-api"); // use this when face-api is installed as module (majority of use cases)

const modelPath = "/Users/srour/imgbreak/node_modules/@vladmandic/face-api/model/";
const ssdOptions = { minConfidence: 0.1, maxResults: 10 };

async function detectFaces(imageFile, callback) {
  try {
    const buffer = fs.readFileSync(imageFile); // read image from disk
    const canvas = await image.imageFromBuffer(buffer); // decode to canvas
    const imageData = image.getImageData(canvas); // read decoded image data from canvas
    //log.info("image:", imageFile, canvas.width, canvas.height);

    const tensor = tf.tidy(() => {
      // create tensor from image data
      const data = tf.tensor(
        Array.from(imageData?.data || []),
        [canvas.height, canvas.width, 4],
        "int32"
      ); // create rgba image tensor from flat array and flip to height x width
      const channels = tf.split(data, 4, 2); // split rgba to channels
      const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
      const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
      return reshape;
    });
    //   log.info("tensor:", tensor.shape, tensor.size);

    // load models
    await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
    await faceapi.nets.ageGenderNet.loadFromDisk(modelPath);
    await faceapi.nets.faceLandmark68Net.loadFromDisk(modelPath);
    await faceapi.nets.faceRecognitionNet.loadFromDisk(modelPath);
    await faceapi.nets.faceExpressionNet.loadFromDisk(modelPath);

    const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions); // create options object
    const result = await faceapi // run detection
      .detectAllFaces(tensor, optionsSSDMobileNet)
      .withFaceLandmarks()
      .withFaceExpressions()
      .withFaceDescriptors()
      .withAgeAndGender();
    //    log.data("results:", result.length);
    //console.log(result);

    delete buffer;
    delete canvas;
    delete imageData;

    return callback(undefined, result.length);
  } catch (e) {
    console.log("Error reading " + imageFile);
    return callback(e, undefined);
  }
}

module.exports.detectFaces = detectFaces;

**Comment by srour** [comment] 2022-03-21 03:40
There are several obvious issues here that I fixed. I moved the model loading into a one time thing and made the buffer variables global to the module so memory wouldn't be re-allocated every time the function ran. These two changes seem to have mitigated the problem significantly.

**Comment by srour** [comment] 2022-03-21 04:54
I did some reading about tensorflow tiny and memory management. I suppose we aren't supposed to call tf.dispose(). This is the current code but it still seems to be leaking tensors as evidence by the tf.memory().numTensors call. Any suggestions?

`const fs = require("fs");
const image = require("@canvas/image"); // @canvas/image can decode jpeg, png, webp
const log = require("@vladmandic/pilogger");
const tf = require("@tensorflow/tfjs-node"); // in nodejs environments tfjs-node is required to be loaded before face-api
const faceapi = require("@vladmandic/face-api"); // use this when face-api is installed as module (majority of use cases)

const modelPath = "/Users/srour/imgbreak/node_modules/@vladmandic/face-api/model/";
const ssdOptions = { minConfidence: 0.1, maxResults: 10 };

var buffer;
var canvas;
var imageData;
var optionsSSDMobileNet;
var tensor;

// load models
async function startup() {
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
  await faceapi.nets.ageGenderNet.loadFromDisk(modelPath);
  await faceapi.nets.faceLandmark68Net.loadFromDisk(modelPath);
  await faceapi.nets.faceRecognitionNet.loadFromDisk(modelPath);
  await faceapi.nets.faceExpressionNet.loadFromDisk(modelPath);

  optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions); // create options object
}

async function detectFaces(imageFile, callback) {
  try {
    buffer = fs.readFileSync(imageFile); // read image from disk
    canvas = await image.imageFromBuffer(buffer); // decode to canvas
    imageData = image.getImageData(canvas); // read decoded image data from canvas
    //log.info("image:", imageFile, canvas.width, canvas.height);

    tensor = tf.tidy(() => {
      // create tensor from image data
      const data = tf.tensor(
        Array.from(imageData?.data || []),
        [canvas.height, canvas.width, 4],
        "int32"
      ); // create rgba image tensor from flat array and flip to height x width
      const channels = tf.split(data, 4, 2); // split rgba to channels
      const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
      const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
      return reshape;
    });
    //   log.info("tensor:", tensor.shape, tensor.size);

    const result = await faceapi // run detection
      .detectAllFaces(tensor, optionsSSDMobileNet)
      .withFaceLandmarks()
      .withFaceExpressions()
      .withFaceDescriptors()
      .withAgeAndGender();
    //    log.data("results:", result.length);
    //console.log(result);

    tf.dispose();

    console.log("numTensors: " + tf.memory().numTensors);

    return callback(undefined, result.length);
  } catch (e) {
    console.log("Error reading " + imageFile);
    return callback(e, undefined);
  }
}

startup();

module.exports.detectFaces = detectFaces;
`

**Comment by vladmandic** [comment] 2022-03-21 05:17
> I suppose we aren't supposed to call `tf.dispose()`

where did you hear that? `faceapi` internally creates tensors and disposes all of them before returning. but you still need to dispose any tensors you created outside of the library.  
but...this line does nothing since you didn't specify what to dispose:

```js
tf.dispose();
```

just change it to

```js
tf.dispose(tensor);
```

**Comment by vladmandic** [comment] 2022-03-22 11:16
@srour any updates?

**Comment by srour** [comment] 2022-03-23 02:45
Thank you so much for getting back to me. It's working pretty well now that I fixed the leaking tensors and added some try/catch blocks. It looks like the image parsing code doesn't like images larger than 1MB, so i'll need to re-evaluate that later. Also, I was running into issues with the code running before the models were loaded so needed to add some basic loading checks. 

Here is the working code:

```
const fs = require("fs");
const image = require("@canvas/image"); // @canvas/image can decode jpeg, png, webp
const log = require("@vladmandic/pilogger");
const tf = require("@tensorflow/tfjs-node"); // in nodejs environments tfjs-node is required to be loaded before face-api
const faceapi = require("@vladmandic/face-api"); // use this when face-api is installed as module (majority of use cases)

const modelPath = "/Users/srour/imgbreak/node_modules/@vladmandic/face-api/model/";
const ssdOptions = { minConfidence: 0.1, maxResults: 10 };

var buffer;
var canvas;
var imageData;
var optionsSSDMobileNet;
var tensor;
var loaded;

// load models
async function startup() {
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
  await faceapi.nets.ageGenderNet.loadFromDisk(modelPath);
  await faceapi.nets.faceLandmark68Net.loadFromDisk(modelPath);
  await faceapi.nets.faceRecognitionNet.loadFromDisk(modelPath);
  await faceapi.nets.faceExpressionNet.loadFromDisk(modelPath);

  optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions); // create options object

  console.log("models loaded...");

  loaded = true;
}

async function detectFaces(imageFile, callback) {
  if (!loaded) return callback("model not loaded yet");

  try {
    fs.stat(imageFile, async function (err, stats) {
      if (err) return callback(err, undefined);
      if (stats.size > 1000000) {
        return callback("too big");
      } else {
        buffer = fs.readFileSync(imageFile); // read image from disk
        try {
          canvas = await image.imageFromBuffer(buffer); // decode to canvas
          imageData = image.getImageData(canvas); // read decoded image data from canvas
        } catch (e) {
          console.log("Error: " + e);
          return callback(e, undefined);
        }
        //log.info("image:", imageFile, canvas.width, canvas.height);
        try {
          tf.engine().startScope();
          tensor = tf.tidy(() => {
            // create tensor from image data
            const data = tf.tensor(
              Array.from(imageData?.data || []),
              [canvas.height, canvas.width, 4],
              "int32"
            ); // create rgba image tensor from flat array and flip to height x width
            const channels = tf.split(data, 4, 2); // split rgba to channels
            const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
            const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead

            return reshape;
          });

          //   log.info("tensor:", tensor.shape, tensor.size);

          const result = await faceapi // run detection
            .detectAllFaces(tensor, optionsSSDMobileNet)
            .withFaceLandmarks()
            .withFaceExpressions()
            .withFaceDescriptors()
            .withAgeAndGender();
          //    log.data("results:", result.length);
          //console.log(result);

          tf.engine().endScope();
          //tf.dispose();

          //console.log("numTensors: " + tf.memory().numTensors);
          return callback(undefined, result.length);
        } catch (e) {
          console.log("tensorflow error: " + e);
          return callback(e, undefined);
        }
      }
    });
  } catch (e) {
    console.log("Error reading " + imageFile + " " + e);
    tf.dispose(tensor);
    return callback(e, undefined);
  }
}

startup();

module.exports.detectFaces = detectFaces;
```

**Comment by vladmandic** [comment] 2022-03-23 09:19
> code running before the models were loaded

instead of  
`if (!loaded) return callback("model not loaded yet");`

i would just do  
`if (!optionsSSDMobileNet ) await startup();`

> it looks like the image parsing code doesn't like images larger than 1MB

i did not see that problem so far. what exactly fails?  

alternatively to using `canvas.js` to decode image, you can use native `tfjs` methods - less flexible, but still pretty good - take a look at `demo/node-simple.js`

anyhow, i'm closing the issue as resolved, but feel free to continue with comments if you have any questions.

**Comment by srour** [comment] 2022-03-31 05:12
Thank you for all of your help - this is awesome.

Things are generally working except after some time I get this crash:

/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:430
        throw new Error(typeof msg === 'string' ? msg : msg());
              ^

Error: Negative size values should be exactly -1 but got -64 for the slice() size at index 0.
    at assert (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:430:15)
    at /Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9723:13
    at Array.map (<anonymous>)
    at Object.parseSliceParams (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9718:19)
    at Object.kernelFunc (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-node/dist/kernels/Slice.js:33:49)
    at kernelFunc (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4570:32)
    at /Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4631:27
    at Engine.scopedRun (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4435:23)
    at Engine.runKernelFunc (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4627:14)
    at Engine.runKernel (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4499:21)

Have you seen something like this before?

**Comment by vladmandic** [comment] 2022-03-31 05:32
i haven't seen that. and unfortunately, the backtrace is too short - it doesn't show which function tried to use `slice()` with incorrect param. you can set a longer backtrace limit so next time it happens there is some detail where error actually started.

**Comment by srour** [comment] 2022-04-04 00:08
This is the full back trace:
/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:430
        throw new Error(typeof msg === 'string' ? msg : msg());
              ^

Error: Negative size values should be exactly -1 but got -8 for the slice() size at index 0.
    at assert (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:430:15)
    at /Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9723:13
    at Array.map (<anonymous>)
    at Object.parseSliceParams (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9718:19)
    at Object.kernelFunc (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-node/dist/kernels/Slice.js:33:49)
    at kernelFunc (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4570:32)
    at /Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4631:27
    at Engine.scopedRun (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4435:23)
    at Engine.runKernelFunc (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4627:14)
    at Engine.runKernel (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4499:21)
    at slice_ (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:12124:19)
    at slice__op (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5450:29)
    at slice3d_ (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:19303:12)
    at Object.slice3d__op (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5450:29)
    at /Users/srour/imgbreak/node_modules/@vladmandic/face-api/dist/face-api.node.js:7:26538
    at Array.map (<anonymous>)
    at /Users/srour/imgbreak/node_modules/@vladmandic/face-api/dist/face-api.node.js:7:26501
    at /Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4425:22
    at Engine.scopedRun (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4435:23)
    at Engine.tidy (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4424:21)
    at Object.tidy (/Users/srour/imgbreak/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:10476:19)
    at re (/Users/srour/imgbreak/node_modules/@vladmandic/face-api/dist/face-api.node.js:7:26369)
    at yr.run (/Users/srour/imgbreak/node_modules/@vladmandic/face-api/dist/face-api.node.js:7:79156)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async yr.then (/Users/srour/imgbreak/node_modules/@vladmandic/face-api/dist/face-api.node.js:7:74360)

Node.js v17.7.2

This looks to be pretty deep into the tensorflow code. 

Interestingly this happens on small image files that are wide, not very tall and with some text on them. No faces.

**Comment by vladmandic** [comment] 2022-04-04 11:36
backtrace does point to error in .slice() op params, but impossible to tell where it comes from and slide op is used in 50+ places in the code. 

key lines are:
```test
at /Users/srour/imgbreak/node_modules/@vladmandic/face-api/dist/face-api.node.js:7:26538
at Array.map ()
at /Users/srour/imgbreak/node_modules/@vladmandic/face-api/dist/face-api.node.js:7:26501
```
but its impossible to map that back to actual metho based on node's backtrace - it doesn't know how to unwrap minified code (browser would do so using provided .map files, node does not).

to move forward, two options:
- if this is regularly reproducible on your system, can you share your code and exact image which exhibits problems?
- if i cannot reproduce, i can provide non-minified version of `face-api.node.js` to you so backtrace would be more readable?

**Comment by srour** [comment] 2022-04-05 01:54
This is a sample that causes the failure. First file calls into the module exposed by the second file. The attached jpeg causes the bug. 

`const sqlite3 = require("sqlite3").verbose();
const util = require("util");
const fs = require("fs");
const path = require("path");
const async = require("async");
const _ = require("underscore");
const face = require("./face.js");
const heapdump = require("heapdump");
Error.stackTraceLimit = Infinity;

const { imageTensorToCanvas } = require("@vladmandic/face-api");

setTimeout(() => {
  var result = face.detectFaces("./test.jpg", function (err, result) {
    console.log(err);
    console.log(result);
  });
}, 5000);
`

`const fs = require("fs");
const image = require("@canvas/image"); // @canvas/image can decode jpeg, png, webp
const log = require("@vladmandic/pilogger");
const tf = require("@tensorflow/tfjs-node"); // in nodejs environments tfjs-node is required to be loaded before face-api
const faceapi = require("@vladmandic/face-api"); // use this when face-api is installed as module (majority of use cases)

const modelPath = "/Users/srour/imgbreak/node_modules/@vladmandic/face-api/model/";
const ssdOptions = { minConfidence: 0.1, maxResults: 10 };

var buffer;
var canvas;
var imageData;
var optionsSSDMobileNet;
var tensor;
var loaded;

// load models
async function startup() {
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
  await faceapi.nets.ageGenderNet.loadFromDisk(modelPath);
  await faceapi.nets.faceLandmark68Net.loadFromDisk(modelPath);
  await faceapi.nets.faceRecognitionNet.loadFromDisk(modelPath);
  await faceapi.nets.faceExpressionNet.loadFromDisk(modelPath);

  optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions); // create options object

  console.log("models loaded...");

  loaded = true;
}

async function detectFaces(imageFile, callback) {
  if (!loaded) return callback("model not loaded yet");

  try {
    fs.stat(imageFile, async function (err, stats) {
      if (err) return callback(err, undefined);
      if (stats.size > 1000000) {
        return callback("too big");
      } else {
        buffer = fs.readFileSync(imageFile); // read image from disk
        try {
          canvas = await image.imageFromBuffer(buffer); // decode to canvas
          imageData = image.getImageData(canvas); // read decoded image data from canvas
          
        } catch (e) {
          console.log("Error: " + e);
          return callback(e, undefined);
        }
        //log.info("image:", imageFile, canvas.width, canvas.height);
        try {
          tf.engine().startScope();
          tensor = tf.tidy(() => {
            // create tensor from image data
            const data = tf.tensor(
              Array.from(imageData?.data || []),
              [canvas.height, canvas.width, 4],
              "int32"
            ); // create rgba image tensor from flat array and flip to height x width
            const channels = tf.split(data, 4, 2); // split rgba to channels
            const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
            const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead

            return reshape;
          });

          //   log.info("tensor:", tensor.shape, tensor.size);

          const result = await faceapi // run detection
            .detectAllFaces(tensor, optionsSSDMobileNet)
            .withFaceLandmarks()
            .withFaceExpressions()
            .withFaceDescriptors()
            .withAgeAndGender();
          //    log.data("results:", result.length);
          //console.log(result);

          tf.engine().endScope();
          //tf.dispose();

          //console.log("numTensors: " + tf.memory().numTensors);
          return callback(undefined, result.length);
        } catch (e) {
          console.log("tensorflow error: " + e);
          return callback(e, undefined);
        }
      }
    });
  } catch (e) {
    console.log("Error reading " + imageFile + " " + e);
    tf.dispose(tensor);
    return callback(e, undefined);
  }
}

startup();

module.exports.detectFaces = detectFaces;
`

![test](https://user-images.githubusercontent.com/748300/161663134-f7d4320e-34a7-415e-96f7-f32ad7922b50.jpg)

**Comment by vladmandic** [comment] 2022-04-05 11:44
this helped, i just posted an updated code on github that should work. can you test it?

unrelated, couple of suggestions
- your entire function executes in a callback of `fs.stat` - don't do that. do await for fs.stat, return if checks fail and continue executions without callback.
- you're nesting multiple try/catch blocks - that never results in what you'd expect. its ok to have multiple try/catch, but do them sequentially, never nested.
- using `tf.startScope` and `tf.endScope` seems ok, but in reality it just hides any problems you might have. rather make sure you don't have memory leaks to start with so you don't need to do forced scoping (for example, you're disposing tensors in catch block, but never dispose it if there is no error)

**Closed by vladmandic** 2022-04-05 11:44 UTC
Labels: question
