### ISSUE TITLE
WebGL silent issues cause empty results on some clients

### ISSUE THREAD

**Issue by smerchkz** [vladmandic/face-api#70] opened 2021-09-30 16:32 UTC
gd,

I switched from version "face-api.js": "0.22.2" to "@vladmandic / face-api": "1.5.3". 
node -v: v14.15.0, 13.latest, v14.15.17
I use face recognition and facematch 2 faces in the browser using react.js

I am faced with the problem that there are users' computers where the code below returns []
```
        const detections = await faceapi
            .detectSingleFace (imageRef.current, faceapi.SsdMobilenetv1Options ())
            .withFaceLandmarks ()
            .withFaceDescriptor ();
        console.log ('fl detection', detections)
```
Chrome browsers of the latest version, Windows is 7, 8, 10. 
For example, on this computes the test https://vladmandic.github.io/face-api/demo/ with girls does not return dots on faces.

tell me which way to dig, what could be the problem?

![Снимок](https://user-images.githubusercontent.com/21982787/135494775-dc7a1a55-12b9-4725-949a-c8419ee9f163.PNG)
![Снимок2](https://user-images.githubusercontent.com/21982787/135494783-208c3cd6-8d4d-4bf9-9d54-08d7a3a5f8cd.PNG)

**Comment by smerchkz** [comment] 2021-09-30 17:26
no i run my code, it is like the example above, it outputs []

but to make sure my code is stupid or the library does not work, I open your demo with girls or with a webcam and it does not generate points. This means that the library does not work not in mine code, but in general in any code on this computer.

I saw 3 such computers today.

after tomorrow we are doing testing for 5000 people and it is critical for us that the library does not work. 
could you help me somehow to fix this moment? what does that require?


[vladmandic.github.io-1633022056256.log](https://github.com/vladmandic/face-api/files/7261378/vladmandic.github.io-1633022056256.log)

**Comment by vladmandic** [comment] 2021-09-30 17:48
its strange since i can see that library gets initialized and models are loaded correctly  
there are no errors at all, just result is empty  

i just pushed an update to `github`, can you check with different backend?
- <https://vladmandic.github.io/face-api/demo/index.html?backend=wasm>
- <https://vladmandic.github.io/face-api/demo/index.html?backend=webgl> 

and post logs from browser inspector for both

**Comment by smerchkz** [comment] 2021-09-30 18:21
thanks for helping

wasp works, webgl it not

[vladmandic.github.io-1633025439972.log](https://github.com/vladmandic/face-api/files/7261681/vladmandic.github.io-1633025439972.log)
[vladmandic.github.io-1633025557629.log](https://github.com/vladmandic/face-api/files/7261682/vladmandic.github.io-1633025557629.log)

**Comment by smerchkz** [comment] 2021-09-30 18:34
remotely via teamviewer
[gpu.txt](https://github.com/vladmandic/face-api/files/7261744/gpu.txt)

**Comment by vladmandic** [comment] 2021-09-30 19:00
There's something between drivers for AMD Radeon R5, TeamViewer and Chrome's implementation of WebGL (Angle) that cause NaN math errors, but Chrome decides to silently drop those instead of reporting them to the app  

Which of the above components is the root cause, I don't know  

But if you're happy using WASM backend, then its not really an issue we should worry about  
(WebGL is faster than WASM if you have a dedicated GPU, but with built-in display adapters such as this one, WebGL doesn't perform any better than WASM)

**Comment by smerchkz** [comment] 2021-09-30 21:21
I understand correctly that my solution for a this computer is:
`faceapi.tf.setBackend ('wasm');`

is there a method that determines which backend will run on the computer better? Or just do the default if it does not work then use wasm?

**Comment by vladmandic** [comment] 2021-09-30 21:47
you need to tell `tfjs` where to find `wasm` binaries before setting backend:

for example, to download them directly from a CDN:
```js
await faceapi.tf.setWasmPaths('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.9.0/dist/');
await faceapi.tf.setBackend(backend);
```

or you can host them yourself and use that path - they are located in `./node_modules/@tensorflow/tfjs-backend-wasm/dist/`

> is there a method that determines which backend will run on the computer better

unfortunately, no - only way would be to run some sort of a benchmark using all possible backends and for benchmark to be meaningful, it would add few seconds to page load time.

> Or just do the default if it does not work then use wasm

your choice. both have pros and cons:
- wasm: requires additional binaries, has faster initial detection (no delays as wasm is precompiled), actual performance depends on cpu
- webgl: no additional binaries, has slower initial detection (webgl functions needs to be compiled and uploaded to gpu), actual performance depends on gpu

**Comment by smerchkz** [comment] 2021-09-30 22:05
I wanted to thank you for your help, do you accept donations?

And the last question for today, after installing your library in package.json, time of creation build in reactjs increased very much, became 3-5 minutes. Is this normal or am I doing something wrong?

```
node -v
v14.15.0
nv-cmd -f ./.env npm run-script build

```

**Comment by vladmandic** [comment] 2021-09-30 22:33
> I wanted to thank you for your help, do you accept donations?

no need, but thanks :)

>after installing your library in package.json, time of creation build in reactjs increased very much, became 3-5 minutes. Is this normal or am I doing something wrong?

i'm assuming you're using `next.js` as the backend for `react`? if yes, `next.js` uses `webpack` internally and it tries to recompile and bundle everything server-side by default (next.js is famous for SSR - server side rendering), even if the module is intended to be used in the front-end  

and that is massive, so yes, build time explodes and the result doesnt work anymore since such *mangled* faceapi gets confused as it doesnt know if its running server-side on nodejs or client-side in browser.

simplest solution is not to use FaceAPI ESM module at all, but to load FaceAPI IIFE version via <script> tag in html. 
or same IIFE via import in the front-end react code - thats what most people do. 

but for proper module support, you need to explicitly configure your environment  

i'm not a react expect, but take a search for older closed issue, this was raised couple of times  

for example, one of my suggestions was: <https://github.com/vladmandic/face-api/issues/42#issuecomment-810403357>

**Comment by vladmandic** [comment] 2021-09-30 22:35
closing the issue as original problem is resolved, but feel free to ask any other questions.

**Closed by vladmandic** 2021-09-30 22:35 UTC
Labels: question
