### ISSUE TITLE
can not recognize face with web page

### ISSUE THREAD

**Issue by GuoSirius** [vladmandic/face-api#154] opened 2023-02-04 08:02 UTC
With the same parameters and electrophoretic method, upgraded to version 1.7, the face on the web side cannot be recognized, and the result is always empty

**Comment by vladmandic** [comment] 2023-02-04 13:28
Can you provide some reproduction? I have nothing to go with.

Any please fill the issue template.

**Comment by vladmandic** [comment] 2023-02-10 17:30
closing due to lack of provided information

**Closed by vladmandic** 2023-02-10 17:30 UTC
Labels: question
