### ISSUE TITLE
Is there WASM support?

### ISSUE THREAD

**Issue by umitkacar** [vladmandic/face-api#28] opened 2020-12-18 19:32 UTC
"Face-api.js" includes "WEBGL" and "CPU". CPU is very slow. I want to use "WASM" for tensorflowjs. Now tensorflowjs supports WASM:

https://blog.tensorflow.org/2020/03/introducing-webassembly-backend-for-tensorflow-js.html

How can I use it with WASM? Tensoflowjs with WASM is below:

https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm

I added "import * as faceapi from './dist/face-api.esm.js';" After that, how can I add with import?

Can you give a example? 

Current tensorflowjs version is 2.7.0. Also, will you update it with tensorflowjs 2.8.1 version?

Thanks for in advance.

**Comment by vladmandic** [comment] 2020-12-19 14:40
`wasm` backend is included and supported in `face-api`, just specify you want to use it.  

you do need to specify where to find wasm binaries (either directly from `node_modules` or copy them somewhere on your web server and point to that location).

for example:
```js
  faceapi.tf.setWasmPaths('../node_modules/@tensorflow/tfjs-backend-wasm/dist/')
  faceapi.tf.setBackend('wasm');
```

i'm testing 2.8.1 for possible upgrade today. 2.8.0 had a regression which was fixed in 2.8.1, but there is still one breaking change that needs addressing.

**Comment by vladmandic** [comment] 2020-12-19 16:49
update: new version of `face-api` with `tfjs` **2.8.1** has been published

**Comment by umitkacar** [comment] 2020-12-19 17:13
You are great!!! Thank you.
Also, Where will I find this path? I search it. But I didn't find it.
faceapi.tf.setWasmPaths('../node_modules/@tensorflow/tfjs-backend-wasm/dist/')

**Comment by vladmandic** [comment] 2020-12-19 17:19
You can find `*.wasm` files online (there are always 3 - basic, simd and threaded.  
for example at <https://www.jsdelivr.com/package/npm/@tensorflow/tfjs-backend-wasm?path=dist>

Or if you install `@tensorflow/tfjs-backend-wasm`, it will contain several `*.wasm` files, just copy those 3 files whereever you want and uininstall `@tensorflow/tfjs-backend-wasm`.

And when using WASM, for performance reason, I suggest to enable SIMD support in your browser.
Take a look at <https://github.com/vladmandic/human/wiki/Backends> for details.

**Comment by umitkacar** [comment] 2020-12-20 20:00
I added it. But I have an error.

wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

falling back to ArrayBuffer instantiation (anonymous)	@	dist/face-api.esm.js:8

**Comment by umitkacar** [comment] 2020-12-21 09:49
I solved this problem using codes below. Flag must be "true". Thank you. 
```js
const usePlatformFetch = true;
faceapi.tf.setWasmPaths('./dist/', usePlatformFetch);
await faceapi.tf.setBackend('wasm');
```

**Closed** 2020-12-21 09:50 UTC
Labels: question

**Comment by vladmandic** [comment] 2020-12-21 12:28
just to explain this one - this seems to be a your web server configuration issue as browser built-in `fetch` (used when `usePlatformFetch` is not set) requested a `WASM` file and did receive, but it was marked as wrong file type (e.g. ASCII instead of binary) so it failed.  

setting `usePlatformFetch` bypassed browser built-in `fetch` and uses a custom implementation inside TFJS which basically ignored request response type.

you can confirm this by looking at browser inspect window network requests - check the response code and header for requested WASM file in both cases.

**Comment by HemantKumar01** [comment] 2021-01-10 08:31
i am trying `faceapi.tf.setWasmPaths('../node_modules/@tensorflow/tfjs-backend-wasm/dist/')` after installing tfjs-backend-wasm in my project, but it is giving error `t.setWasmPaths is not a function`

**Comment by vladmandic** [comment] 2021-01-10 13:57
I just tried enabling WASM in provided demo using FaceAPI with TFJS pre-bundled and it works out-of-the-box:

`example/index.js`:
```js
  import * as faceapi from '../dist/face-api.esm.js';
  ...

  // if you want to use wasm backend location for wasm binaries must be specified
  await faceapi.tf.setWasmPaths('../node_modules/@tensorflow/tfjs-backend-wasm/dist/');
  await faceapi.tf.setBackend('wasm');

  // default is webgl backend
  // await faceapi.tf.setBackend('webgl');
```

```
FaceAPI Test
Version: TensorFlow/JS 2.8.3 FaceAPI faceapi:0.10.2, node:false, browser:true Backend: wasm
Flags: {"IS_BROWSER":true,"IS_NODE":false,"DEBUG":false,"WASM_HAS_SIMD_SUPPORT":true,"WASM_HAS_MULTITHREAD_SUPPORT":true,"PROD":true}
Loading FaceAPI models
...
```

But if you're not using `nobundle` version of FaceAPI, then yes, your procedure is correct.

**Comment by deylyn** [comment] 2021-04-08 22:25
where do i find face-api.esm.js?

**Comment by vladmandic** [comment] 2021-04-08 22:30
@deylyn `face-api.esm.js` is a part of this package.  
install NPM package, download it from `/dist/` folder or use directly from a CDN - either works.  
and see demos for examples.  

it's all covered in the **README**
